development:
  options: 
    raise_not_found_error: false
  sessions:
    default:
      database: creator
      hosts:
        - localhost:27017
test:
  options: 
    raise_not_found_error: false
  sessions:
    default:
      database: creator_test
      allow_dynamic_fields: true
      raise_not_found_error:
      hosts:
        - localhost:27017